const AM = 'am|a.m.|am.';
const PM = 'pm|p.m.|pm.';
const MERIDIEM = `(${AM}|${PM})`;
const FILLER_WORDS = '(at|by)';
const HOUR_PART = '([0-9]{1,2})';
const DIVIDER = '(:)';
const MINUTE_PART = '([0-9]{1,2})';
const TO = '(to|until)';
const PAST = '(after|past)';
const RELATIVE_TIME_FILLER_WORDS = `(${TO}|${PAST})`;
const HALF = 'half';
const QUARTER = 'quarter';
const VERBAL_QUANTIFIERS = `(${HALF}|${QUARTER})`;
const MINUTE_IDENTIFIER = '(min|mins|minutes)';

const FORMAT_JUST_HOUR = `${HOUR_PART}( )?${MERIDIEM}`; // 4am or 4 am
const FORMAT_HOUR_WITH_MINS = `${HOUR_PART}${DIVIDER}${MINUTE_PART}`; // 04:30
const FORMAT_HOUR_WITH_MINS_AND_MERIDIEM = `${HOUR_PART}${DIVIDER}${MINUTE_PART}( )?${MERIDIEM}`; // 04:30am or 04:30 am
const FROMAT_VERBAL_QUANTIFIERS = `${VERBAL_QUANTIFIERS}( )${RELATIVE_TIME_FILLER_WORDS}( )(${HOUR_PART}( )?${MERIDIEM}|${HOUR_PART})`; // half past 3pm
const FROMAT_DIGIT_RELATIVE = `${MINUTE_PART}( )(${MINUTE_IDENTIFIER}( ))?${RELATIVE_TIME_FILLER_WORDS}( )(${HOUR_PART}( )?${MERIDIEM}|${HOUR_PART})`; // 20 mins to 11
const FORMAT_NORMAL_TIME = `(${FORMAT_JUST_HOUR}|${FORMAT_HOUR_WITH_MINS_AND_MERIDIEM}|${FORMAT_HOUR_WITH_MINS})`;
const FORMAT_RELATIVE_TIME = `(${FROMAT_VERBAL_QUANTIFIERS}|${FROMAT_DIGIT_RELATIVE})`;

const TIME = {
    ANY: `(${FORMAT_NORMAL_TIME}|${FORMAT_RELATIVE_TIME})`,
    FORMAT_NORMAL: FORMAT_NORMAL_TIME,
    FORMAT_RELATIVE: FORMAT_RELATIVE_TIME,
    RELATIVE_TIME_FILLER_WORDS,
    HOUR_PART,
    MINUTE_PART,
    DIVIDER,
    MERIDIEM,
    AM,
    PM,
    TO,
    PAST,
    HALF,
    QUARTER,
    VERBAL_QUANTIFIERS,
    MINUTE_IDENTIFIER,
    FILLER_WORDS,
};

export default TIME;
