name: Prepare
description: Prepare PNPM and Node
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v5
      with:
        version: 7
    - uses: actions/setup-node@v6
      with:
        node-version-file: ".nvmrc"
        cache: 'pnpm'
