name: Prepare
description: Prepare PNPM and Node
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v5
    - uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
        package-manager-cache: false # never use caching in release builds
        registry-url: 'https://registry.npmjs.org'
