name: Pull Request Validate

on:
  pull_request:
    branches:
      - master

concurrency:
  cancel-in-progress: true

jobs:
    lint-check:
      name: Lint check
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Run lint check
          shell: bash
          run: pnpm lint

    unit-tests:
      name: Unit tests
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Run unit tests
          shell: bash
          run: pnpm test:ci

    build-check:
      name: Build check
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Run build check
          shell: bash
          run: pnpm build
    
    test-coverage:
      name: Test Coverage
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: ArtiomTr/jest-coverage-report-action@v2
          id: coverage
          with:
              output: report-markdown
        - uses: marocchino/sticky-pull-request-comment@v2
          with:
              message: ${{ steps.coverage.outputs.report }}


